# Generated by Django 4.1.2 on 2022-10-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="owner",
        ),
    ]
